package translation

import (
	"cmp"
	"math"
	"slices"
	"strings"
	"unicode/utf8"

	"github.com/wolf29f/hushtongue/internal/services/generator"
	"github.com/wolf29f/hushtongue/internal/services/storage"
)

// minRootLength is the minimum length, in characters, of a root left once
// the affixes are stripped.
const minRootLength = 2

// Proposal is a way to translate a source word: its parts, in the order
// prefixes, root, suffixes.
type Proposal struct {
	Parts []storage.TranslationPart
}

func (p Proposal) known() int {
	count := 0
	for _, part := range p.Parts {
		if part.ConID != 0 {
			count++
		}
	}
	return count
}

// rank orders the proposals: complete existing translations first, pure
// generation last, the others by number of known parts.
func (p Proposal) rank() int {
	if len(p.Parts) == 1 {
		if p.Parts[0].ConID != 0 {
			return math.MaxInt
		}
		return math.MinInt
	}
	return p.known()
}

// Service builds and applies translation proposals.
type Service struct {
	storage storage.Storage
}

// New creates a translation service on top of storage.
func New(storage storage.Storage) *Service {
	return &Service{storage: storage}
}

// Propose lists the ways to translate the source word wordID, best first.
// Roots are decomposed into known affixes and a root, affixes are not.
func (s *Service) Propose(wordID int) ([]Proposal, error) {
	word, err := s.storage.GetWord(wordID)
	if err != nil {
		return nil, err
	}
	sources, err := s.storage.ListWordDetails(storage.LangSource)
	if err != nil {
		return nil, err
	}
	cons, err := s.storage.ListWordDetails(storage.LangCon)
	if err != nil {
		return nil, err
	}

	b := builder{
		storage:   s.storage,
		roots:     make(map[string]storage.WordDetails),
		taken:     make(map[string]map[string]bool),
		generated: make(map[string]string),
	}
	for _, source := range sources {
		switch source.Kind {
		case storage.KindPrefix:
			b.prefixes = append(b.prefixes, source)
		case storage.KindSuffix:
			b.suffixes = append(b.suffixes, source)
		default:
			b.roots[source.Normalized] = source
		}
	}
	for _, con := range cons {
		b.take(con.Kind, con.Normalized)
	}

	segmentations := [][]section{{known(word)}}
	if word.Kind == storage.KindRoot {
		segmentations = b.segment(word)
	}

	var proposals []Proposal
	for _, segmentation := range segmentations {
		translated, err := b.translate(segmentation)
		if err != nil {
			return nil, err
		}
		proposals = append(proposals, translated...)
	}

	slices.SortStableFunc(proposals, func(a, b Proposal) int {
		return cmp.Compare(b.rank(), a.rank())
	})
	return proposals, nil
}

// Apply stores the proposal as a translation of the source word wordID.
func (s *Service) Apply(wordID int, proposal Proposal) error {
	return s.storage.SaveGeneratedTranslation(wordID, proposal.Parts)
}

// section is a part of the source word, with the normalized form its
// translation is generated from.
type section struct {
	part       storage.TranslationPart
	normalized string
}

func known(word storage.WordDetails) section {
	return section{
		part: storage.TranslationPart{
			Kind:     word.Kind,
			SourceID: word.ID,
			Source:   word.Text,
		},
		normalized: word.Normalized,
	}
}

type builder struct {
	storage storage.Storage

	prefixes []storage.WordDetails
	suffixes []storage.WordDetails
	roots    map[string]storage.WordDetails // by normalized form

	// taken holds the normalized con words, by kind, generated ones included
	taken map[string]map[string]bool
	// generated holds the con words generated by kind and normalized source
	generated map[string]string
}

func (b *builder) take(kind, con string) {
	if b.taken[kind] == nil {
		b.taken[kind] = make(map[string]bool)
	}
	b.taken[kind][con] = true
}

// segment lists every decomposition of the word into known prefixes, a root
// and known suffixes, the whole word as root included.
func (b *builder) segment(word storage.WordDetails) [][]section {
	normalized := word.Normalized
	var segmentations [][]section

	var stripSuffixes func(start, end int, prefixes, suffixes []section)
	stripSuffixes = func(start, end int, prefixes, suffixes []section) {
		segmentations = append(segmentations, slices.Concat(prefixes, []section{b.root(word, start, end)}, suffixes))
		for _, suffix := range b.suffixes {
			rest := normalized[start:end]
			if suffix.Normalized == "" || !strings.HasSuffix(rest, suffix.Normalized) {
				continue
			}
			if utf8.RuneCountInString(rest)-utf8.RuneCountInString(suffix.Normalized) < minRootLength {
				continue
			}
			stripSuffixes(start, end-len(suffix.Normalized), prefixes, slices.Concat([]section{known(suffix)}, suffixes))
		}
	}

	var stripPrefixes func(start int, prefixes []section)
	stripPrefixes = func(start int, prefixes []section) {
		stripSuffixes(start, len(normalized), prefixes, nil)
		for _, prefix := range b.prefixes {
			rest := normalized[start:]
			if prefix.Normalized == "" || !strings.HasPrefix(rest, prefix.Normalized) {
				continue
			}
			if utf8.RuneCountInString(rest)-utf8.RuneCountInString(prefix.Normalized) < minRootLength {
				continue
			}
			stripPrefixes(start+len(prefix.Normalized), slices.Concat(prefixes, []section{known(prefix)}))
		}
	}

	stripPrefixes(0, nil)
	return segmentations
}

// root returns the root at bytes [start:end) of the word's normalized form.
// An unknown root keeps the word's text, affixes stripped.
func (b *builder) root(word storage.WordDetails, start, end int) section {
	normalized := word.Normalized[start:end]
	if root, ok := b.roots[normalized]; ok {
		return known(root)
	}

	text := normalized
	runes := []rune(word.Text)
	if len(runes) == utf8.RuneCountInString(word.Normalized) {
		from := utf8.RuneCountInString(word.Normalized[:start])
		to := utf8.RuneCountInString(word.Normalized[:end])
		text = string(runes[from:to])
	}

	return section{
		part:       storage.TranslationPart{Kind: storage.KindRoot, Source: text},
		normalized: normalized,
	}
}

// translate returns a proposal per combination of the sections' translations.
func (b *builder) translate(sections []section) ([]Proposal, error) {
	proposals := []Proposal{{}}
	for _, s := range sections {
		options, err := b.options(s)
		if err != nil {
			return nil, err
		}

		next := make([]Proposal, 0, len(proposals)*len(options))
		for _, proposal := range proposals {
			for _, option := range options {
				next = append(next, Proposal{Parts: slices.Concat(proposal.Parts, []storage.TranslationPart{option})})
			}
		}
		proposals = next
	}
	return proposals, nil
}

// options returns the section's existing translations, or a generated one.
func (b *builder) options(s section) ([]storage.TranslationPart, error) {
	if s.part.SourceID != 0 {
		translations, err := b.storage.ListTranslations(s.part.SourceID)
		if err != nil {
			return nil, err
		}
		if len(translations) > 0 {
			options := make([]storage.TranslationPart, len(translations))
			for i, translation := range translations {
				options[i] = s.part
				options[i].ConID = translation.Word.ID
				options[i].Con = translation.Word.Text
			}
			return options, nil
		}
	}

	part := s.part
	part.Con = b.generate(s.normalized, part.Kind)
	return []storage.TranslationPart{part}, nil
}

// generate returns the con word generated for the normalized source, always
// the same one for a given source, and never one taken by another word.
func (b *builder) generate(normalized, kind string) string {
	key := kind + "/" + normalized
	if con, ok := b.generated[key]; ok {
		return con
	}

	con := generator.Generate(normalized, generatorKind(kind), func(word string) bool {
		return b.taken[kind][word]
	})
	b.take(kind, con)
	b.generated[key] = con
	return con
}

func generatorKind(kind string) generator.Kind {
	switch kind {
	case storage.KindPrefix:
		return generator.KindPrefix
	case storage.KindSuffix:
		return generator.KindSuffix
	default:
		return generator.KindRoot
	}
}
